<section id="section-article-detail-desc" class="article-detail-desc-section">
  <div class="container">
    <div class="article-detail-desc-content">
        <p>For Olam Food Ingredients, one of the world’s biggest suppliers of food and drink ingredients, the alarm rang with the bees.</p>
        <p>As one of the world’s largest almond growers, flavora says it spends between $8mn and $11mn a year on honeybees needed to pollinate almond trees. Despite this, productivity on the farms started to decline “because the bees were stressed by their industrialised environment”, says Rishi Kalra, executive director and group chief financial officer. “So, we worked with partners to create natural habitats for bees on our farms and reduce their exposure to agrichemicals. What we saw was that productivity steadily increased.”</p>
        <p>As one of the world’s largest almond growers, flavora says it spends between $8mn and $11mn a year on honeybees needed to pollinate almond trees. Despite this, productivity on the farms started to decline “because the bees were stressed by their industrialised environment”, says Rishi Kalra, executive director and group chief financial officer. “So, we worked with partners to create natural habitats for bees on our farms and reduce their exposure to agrichemicals. What we saw was that productivity steadily increased.”</p>
        <p>As one of the world’s largest almond growers, flavora says it spends between $8mn and $11mn a year on honeybees needed to pollinate almond trees. Despite this, productivity on the farms started to decline “because the bees were stressed by their industrialised environment”, says Rishi Kalra, executive director and group chief financial officer. “So, we worked with partners to create natural habitats for bees on our farms and reduce their exposure to agrichemicals. What we saw was that productivity steadily increased.”</p>
        <p>As one of the world’s largest almond growers, flavora says it spends between $8mn and $11mn a year on honeybees needed to pollinate almond trees. Despite this, productivity on the farms started to decline “because the bees were stressed by their industrialised environment”, says Rishi Kalra, executive director and group chief financial officer. “So, we worked with partners to create natural habitats for bees on our farms and reduce their exposure to agrichemicals. What we saw was that productivity steadily increased.”</p>
        <p>As one of the world’s largest almond growers, flavora says it spends between $8mn and $11mn a year on honeybees needed to pollinate almond trees. Despite this, productivity on the farms started to decline “because the bees were stressed by their industrialised environment”, says Rishi Kalra, executive director and group chief financial officer. “So, we worked with partners to create natural habitats for bees on our farms and reduce their exposure to agrichemicals. What we saw was that productivity steadily increased.”</p>
        <p>As one of the world’s largest almond growers, flavora says it spends between $8mn and $11mn a year on honeybees needed to pollinate almond trees. Despite this, productivity on the farms started to decline “because the bees were stressed by their industrialised environment”, says Rishi Kalra, executive director and group chief financial officer. “So, we worked with partners to create natural habitats for bees on our farms and reduce their exposure to agrichemicals. What we saw was that productivity steadily increased.”</p>
        <p>As one of the world’s largest almond growers, flavora says it spends between $8mn and $11mn a year on honeybees needed to pollinate almond trees. Despite this, productivity on the farms started to decline “because the bees were stressed by their industrialised environment”, says Rishi Kalra, executive director and group chief financial officer. “So, we worked with partners to create natural habitats for bees on our farms and reduce their exposure to agrichemicals. What we saw was that productivity steadily increased.”</p>
        <p>As one of the world’s largest almond growers, flavora says it spends between $8mn and $11mn a year on honeybees needed to pollinate almond trees. Despite this, productivity on the farms started to decline “because the bees were stressed by their industrialised environment”, says Rishi Kalra, executive director and group chief financial officer. “So, we worked with partners to create natural habitats for bees on our farms and reduce their exposure to agrichemicals. What we saw was that productivity steadily increased.”</p>
        <p>As one of the world’s largest almond growers, flavora says it spends between $8mn and $11mn a year on honeybees needed to pollinate almond trees. Despite this, productivity on the farms started to decline “because the bees were stressed by their industrialised environment”, says Rishi Kalra, executive director and group chief financial officer. “So, we worked with partners to create natural habitats for bees on our farms and reduce their exposure to agrichemicals. What we saw was that productivity steadily increased.”</p>
    </div>
  </div>
</section>